# Generated by Django 5.2 on 2025-12-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_alter_profile_name_alter_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_bg_img',
            field=models.ImageField(blank=True, default='https://url-shortener.me/4ZOD', upload_to='profiles/backgrounds/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='https://url-shortener.me/4ZO9', upload_to='profiles/'),
        ),
    ]
