# Generated by Django 5.2 on 2025-12-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_alter_profile_profile_bg_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_bg_img',
            field=models.ImageField(blank=True, default='profiles/backgrounds/default-bg.png', upload_to='profiles/backgrounds/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='profiles/default-profile.png', upload_to='profiles/'),
        ),
    ]
