# Generated by Django 5.2 on 2025-12-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_alter_profile_profile_bg_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('cover_img', models.ImageField(blank=True, default='projects/default-project.png', upload_to='projects/')),
                ('button_text', models.CharField(max_length=32)),
                ('button_link', models.URLField()),
            ],
        ),
    ]
