# Generated by Django 5.2 on 2025-12-24 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_porject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porject',
            name='button_link',
        ),
    ]
