# Generated by Django 5.2 on 2025-12-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_remove_porject_button_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('bg_image', models.ImageField(default='project_hubs/default-hub.png', upload_to='project_hubs/')),
            ],
        ),
    ]
