# Generated by Django 5.2 on 2025-12-24 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0007_projecthub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecthub',
            old_name='title',
            new_name='name',
        ),
    ]
