# Generated by Django 5.2 on 2025-12-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0008_rename_title_projecthub_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectHub',
        ),
    ]
