# Generated by Django 5.2 on 2025-12-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0009_projects_delete_projecthub'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
