# Generated by Django 5.2 on 2025-12-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0010_projects_slug_alter_projects_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_type',
            field=models.CharField(choices=[('english', 'English'), ('art', 'Art'), ('science', 'Science'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
