# Generated by Django 5.2 on 2025-12-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0011_projects_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_type',
        ),
    ]
