# Generated by Django 5.2 on 2025-12-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0012_remove_projects_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_title', models.CharField(max_length=200)),
                ('p_desc', models.TextField()),
                ('p_goal_title', models.CharField(max_length=200)),
                ('p_goal_desc', models.TextField()),
                ('p_final_look_title', models.CharField(max_length=200)),
                ('p_final_look_desc', models.TextField()),
                ('p_conclusion_title', models.CharField(max_length=200)),
                ('p_conclusion_desc', models.TextField()),
                ('p_bibliography_title', models.CharField(max_length=200)),
                ('p_bibliography_desc', models.TextField()),
                ('p_main_img', models.ImageField(upload_to='project_details_img/main/')),
                ('p_conclusion_img', models.ImageField(upload_to='project_details_img/conclusion/')),
                ('p_bibliography_img_1', models.ImageField(upload_to='project_details_img/bibliography_1/')),
                ('p_bibliography_img_2', models.ImageField(upload_to='project_details_img/bibliography_2/')),
            ],
        ),
    ]
