# Generated by Django 5.2 on 2025-12-26 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0013_project_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_details',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='portfolios.projects'),
        ),
    ]
