# Generated by Django 5.2 on 2025-12-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0014_project_details_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_details',
            name='p_bibliography_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='p_bibliography_img_1',
            field=models.ImageField(blank=True, null=True, upload_to='project_details_img/bibliography_1/'),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='p_bibliography_img_2',
            field=models.ImageField(blank=True, null=True, upload_to='project_details_img/bibliography_2/'),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='p_bibliography_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='p_conclusion_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='p_conclusion_img',
            field=models.ImageField(blank=True, null=True, upload_to='project_details_img/conclusion/'),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='p_conclusion_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='p_final_look_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='p_final_look_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='p_goal_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='p_goal_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='p_main_img',
            field=models.ImageField(blank=True, null=True, upload_to='project_details_img/main/'),
        ),
    ]
