# Generated by Django 5.2 on 2025-12-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0016_projectimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='caption',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
