# Generated by Django 5.2 on 2025-12-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0017_remove_projectimage_caption_projectimage_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
